runtime: python311
entrypoint: gunicorn -b :$PORT myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"

manual_scaling:
  instances: 15

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto