runtime: python311
entrypoint: gunicorn -b :$PORT myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"

instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto